#!/usr/bin/env bash
# Run the XCTest sources without Xcode.
#
# Companion to typecheck-tests.sh: same in-module trick, same stand-ins in
# scripts/xctest-shim.swift, but it compiles and *runs* the tests instead of only
# type-checking them. `swift test` needs the XCTest module, which ships only with
# full Xcode, so on a Command Line Tools-only machine this is the difference
# between a green run you can see in seconds and waiting on CI.
#
# `swift test` (via `make test`, or CI) remains the authority. This runs the
# tests serially in one process against hand-written stand-ins and knows nothing
# about XCTest's isolation, parallelism or timeouts. Treat a green run here as
# "worth pushing", not "verified".
#
# Test discovery is by pattern, so it asserts its own count against the declared
# `func test` count and fails on any mismatch. A method it quietly failed to pick
# up would make a green run mean less than it appears to.
#
# Usage: scripts/run-tests-without-xcode.sh [name-filter]
#   name-filter  optional substring; only matching Class.method are run.

set -euo pipefail

cd "$(dirname "$0")/.."

SHIM="scripts/xctest-shim.swift"
TESTS_DIR="Tests/StackNudgePanelCoreTests"
FILTER="${1:-}"

if [[ ! -f "$SHIM" ]]; then
  echo "missing $SHIM" >&2
  exit 1
fi

stage="$(mktemp -d)"
trap 'rm -rf "$stage"' EXIT

runner="$stage/XCTRunner.swift"
{
  echo "// Generated by scripts/run-tests-without-xcode.sh - not a source file."
  echo "import Foundation"
  echo "@main"
  echo "enum XCTRunner {"
  echo "    @MainActor static func main() {"
} > "$runner"

# Same import swap as typecheck-tests.sh: XCTest is replaced rather than deleted
# because it re-exports Foundation, and @testable is dropped since the tests
# compile as part of the panel module here.
declared=0
for source in "$TESTS_DIR"/*.swift; do
  sed -e 's/^import XCTest$/import AppKit\nimport SwiftUI/' \
      -e 's/^@testable import StackNudgePanelCore$//' \
      "$source" > "$stage/$(basename "$source")"
  declared=$((declared + $(grep -cE '^    func test' "$source" || true)))

  # Emit a call per test method, in file order. `throws` variants get a try?;
  # setUp/tearDown bracket each one, as real XCTest does.
  awk '
    /^final class .* XCTestCase \{|^class .* XCTestCase \{/ {
      match($0, /class [A-Za-z0-9_]+/)
      cls = substr($0, RSTART + 6, RLENGTH - 6)
      next
    }
    /^    func test[A-Za-z0-9_]*\(\)/ {
      match($0, /test[A-Za-z0-9_]*/)
      fn = substr($0, RSTART, RLENGTH)
      call = (index($0, "throws") > 0) ? "try? " : ""
      if (cls != "") {
        printf "        run(\"%s.%s\") { let c = %s(); c.setUp(); %sc.%s(); c.tearDown() }\n", \
               cls, fn, cls, call, fn
      }
    }
  ' "$stage/$(basename "$source")" >> "$runner"
done

{
  echo "        report()"
  echo "    }"
  echo ""
  echo "    @MainActor static func run(_ name: String, _ body: () -> Void) {"
  echo "        if !filter.isEmpty, !name.contains(filter) { return }"
  echo "        let before = xctFailures.count"
  echo "        xctTeardowns = []"
  echo "        body()"
  echo "        for block in xctTeardowns.reversed() { try? block() }"
  echo "        xctTeardowns = []"
  echo "        ran += 1"
  echo "        let added = xctFailures.count - before"
  echo "        if added == 0 {"
  echo "            print(\"  ok    \\(name)\")"
  echo "        } else {"
  echo "            print(\"  FAIL  \\(name)\")"
  echo "            for failure in xctFailures.suffix(added) { print(\"          \\(failure)\") }"
  echo "        }"
  echo "    }"
  echo ""
  echo "    static func report() {"
  echo "        print(\"\")"
  echo "        print(\"\\(ran) test(s), \\(xctAssertions) assertion(s), \\(xctFailures.count) failure(s)\")"
  echo "        exit(xctFailures.isEmpty ? 0 : 1)"
  echo "    }"
  echo "}"
  echo ""
  echo "nonisolated(unsafe) var ran = 0"
  printf 'let filter = "%s"\n' "$FILTER"
} >> "$runner"

discovered=$(grep -c 'run("' "$runner" || true)
echo "discovered $discovered of $declared declared test method(s)"
if [[ "$discovered" -ne "$declared" ]]; then
  echo "MISMATCH: $((declared - discovered)) test method(s) were not picked up." >&2
  echo "Discovery is pattern-based; fix it before trusting this run." >&2
  exit 1
fi

# panel/main.swift owns the app entry point, and the generated runner owns @main
# here, so it is excluded. build.sh compiles it as part of the real build.
sources=()
for source in panel/*.swift shared/*.swift; do
  [[ "$source" == "panel/main.swift" ]] && continue
  sources+=("$source")
done

# -suppress-warnings for the same reason typecheck-tests.sh does it: panel/
# carries a stack of pre-existing macOS 14 deprecation warnings that bury
# anything useful. build.sh and CI still report them.
swiftc -suppress-warnings \
  "${sources[@]}" "$SHIM" "$stage"/*.swift \
  -o "$stage/xctest-runner" \
  -framework Foundation -framework AppKit -framework SwiftUI -framework Carbon \
  -framework UserNotifications

"$stage/xctest-runner"
